import { Outfit, Poppins } from "next/font/google";
import "./globals.css";
import { StateContextProvider } from "./context/state";

const outfit = Outfit({
  subsets: ["latin"],
  weights: [400, 500, 600, 700],
  styles: ["italic"],
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  preload: false,
  variable: "--font-poppins"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${poppins.variable}`}>
        <StateContextProvider>
          {children}
        </StateContextProvider>
      </body>
    </html>
  );
}
